include:
  - local: 'ci/job-templates/all.yaml'

stages:
  - tagging
  - build-image
  - deploy

variables:
  bank_address: "outbe140fehngcrxvhdt84x729p3f0qmkmea8nqxn3gl"
  CHAIN_ID: "localchain_90001-1"
  FEE_DENOM: "outbe"
  RPC: "http://localhost:26657"
  CONTRACT_NAME: "your_contract_name"
  INIT_PAYLOAD_PATH: "/contracts/init_payloads/your_contract_name.json"


build-job:
  extends: .build-image
  script:
    - source version.env
    - echo "Contracts container ${IMAGE_PATH}"
    - docker pull $IMAGE_PATH
    - docker create --name tmp-outbe $IMAGE_PATH true
    - docker cp tmp-outbe:/contracts ./contracts
    - docker rm tmp-outbe
  artifacts:
    paths:
      - contracts/
    expire_in: 1 hour


deploy_contract:
  stage: deploy
  dependencies:
    - build-job
  script:
    - echo "$DEPLOYER_MNEMONIC" | outbe-noded keys add deployer --recover --output json --keyring-backend test
    - export deployer_address=$(outbe-noded keys show deployer -a --keyring-backend test)
    - echo "Deployer address: $deployer_address"
    - outbe-noded tx bank send $bank_address $deployer_address 100000000${FEE_DENOM} --chain-id $CHAIN_ID --from acc0 -y --node $RPC
    - filename=contracts/wasm32-unknown-unknown/release/cw20_copy.wasm
    - echo "Uploading contract: $filename"
    - >
      TX_HASH=$(outbe-noded tx wasm store $filename -y --from deployer --broadcast-mode sync
      --node $RPC --chain-id $CHAIN_ID --gas auto --gas-adjustment 1.3 --output json
      --keyring-backend test | jq -r '.txhash') && echo $TX_HASH > tx_hash.txt
    - sleep 7
    - export TX_HASH=$(cat tx_hash.txt)
    - >
      CODE_ID=$(outbe-noded query tx --type=hash $TX_HASH --node $RPC --output json |
      jq -r '.events[] | select(.type == "store_code") | .attributes[] | select(.key == "code_id") | .value') &&
      echo $CODE_ID > code_id.txt
    - export CODE_ID=$(cat code_id.txt)
    - INIT_TEMPLATE=$(cat $INIT_PAYLOAD_PATH)
    - INIT_PAYLOAD=$(echo "$INIT_TEMPLATE" | sed "s/\$bank_address/$bank_address/g" | sed "s/\$deployer_address/$deployer_address/g")
    - echo "Init payload: $INIT_PAYLOAD"
    - >
      TX_HASH=$(outbe-noded tx wasm instantiate $CODE_ID "$INIT_PAYLOAD" --label "$CONTRACT_NAME"
      --from deployer -y --admin $deployer_address --node $RPC --chain-id $CHAIN_ID
      --gas auto --gas-adjustment 1.3 --output json --keyring-backend test | jq -r '.txhash') &&
      echo $TX_HASH > inst_tx_hash.txt
    - sleep 7
    - export TX_HASH=$(cat inst_tx_hash.txt)
    - >
      ADDRESS=$(outbe-noded query tx --type=hash $TX_HASH --node $RPC --output json |
      jq -r '.events[] | select(.type == "instantiate") | .attributes[] | select(.key == "_contract_address") | .value')
    - echo "Contract deployed at: $ADDRESS"