# These values are merged into every system helmfile default values
chartRegistry: "oci://helm-registry.base.our-own.cloud"
secretPath: "ref+awssecrets://environment/"
useSentry: true
ingress:
  baseDomain: "our-own.cloud"
tracing:
  agent:
    host: "collector.opentelemetry.svc.cluster.local"
    port: 6831
sentry:
  projectClass: '{{ if eq .Values.environment "production" }}prod{{ else }}dev{{ end }}'
